# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: Angular SSR & CSR - PROD

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build:ssr
  displayName: 'npm install and build'
- task: replacetokens@5
  inputs:
    rootDirectory: 'dist/angular-ssr-csr-hybrid/browser/'
    targetFiles: 'main*.js'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true
- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/angular-ssr-csr-hybrid/server/'
    Contents: '**'
    TargetFolder: 'new-dist/'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/angular-ssr-csr-hybrid/'
    Contents: '**'
    TargetFolder: 'new-dist/dist/angular-ssr-csr-hybrid/'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/new-dist/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'