# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build:ssr
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/angular-ssr-csr-hybrid/server'
    Contents: '**'
    TargetFolder: 'client/angular-ssr-csr-hybrid/deploy-dist'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist/angular-ssr-csr-hybrid/browser'
    Contents: '**'
    TargetFolder: 'client/angular-ssr-csr-hybrid/deploy-dist/browser'
- task: CmdLine@2
  inputs:
    script: 'mv "client/angular-ssr-csr-hybrid/deploy-dist/main.js" "client/angular-ssr-csr-hybrid/deploy-dist/index.js"'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'client/angular-ssr-csr-hybrid/deploy-dist'
    replaceExistingArchive: true